name: Basic Reusable Workflow Test

on:
  workflow_dispatch:

jobs:
  test-reusable-workflow:
    permissions:
      contents: read     # Ensure the workflow can be read from a private repo
    uses: j-r-manalo/temp-reuesable/.github/workflows/simple-reusable.yml@f13aab874516d18f31019e5b67155e2005478b87
